---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: kami-os
# description will be included in the image's metadata
description: This is a dumb idea.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # always one generation behind latest release for stability

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/hazel-bunny/ricing/repo/fedora-42/hazel-bunny-ricing-fedora-42.repo
      - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      - https://copr.fedorainfracloud.org/coprs/val-byte/branding/repo/fedora-42/val-byte-branding-fedora-42.repo
    install:
      - micro
      - starship
      - alacritty
      - gnome-tweaks
      - kora-icon-theme
      - https://kojipkgs.fedoraproject.org//packages/libXScrnSaver/1.2.4/5.fc42/x86_64/libXScrnSaver-1.2.4-5.fc42.x86_64.rpm
      - fastfetch
      - adwaita-fonts-all
      - legcord
      - kami-os-logos
      - docker
      - docker-compose
      - tailscale
      - ddcutil
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - fedora-logos

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: Flathub
        install:
           - org.gnome.Loupe
           - org.vinegarhq.Sober
           - org.vinegarhq.Vinegar
           - org.pulseaudio.pavucontrol
           - io.mpv.Mpv
           - org.gnome.Extensions
           - com.mattjakeman.ExtensionManager
           - io.github.pwr_solaar.solaar
           - app.zen_browser.zen
           - io.github.hakuneko.HakuNeko
        remove:
           - org.gnome.eog
   
  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
      - Just Perfection
      - Dash to Dock
      - Control monitor brightness and volume with ddcutil
    
  - type: bling
    install:
      - rpmfusion
      
  - type: os-release
    properties:
      ID: kami_os
      NAME: Kami-OS
      PRETTY_NAME: Kami-OS
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
