---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: kami-os
# description will be included in the image's metadata
description: This is a dumb idea.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # always one generation behind latest release for stability

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - val-byte/branding
    install:
      packages:
        - starship
        - fastfetch
        - kami-os-logos
        - tailscale
        - ddcutil
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - fedora-logos
        - gnome-software
      
  - type: containerfile
    snippets:
      - |
        RUN dnf5 -y install oras tar && \
            mkdir -p /tmp/ogc-rpms && \
            oras pull ghcr.io/opengamingcollective/kernel-packages-fedora:latest-fc43 -o /tmp/ogc-rpms && \
            dnf5 -y install $(find /tmp/ogc-rpms -name "kernel-*.rpm") --allow-downgrade --allowerasing && \
            rm -rf /tmp/ogc-rpms
            
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: Flathub
        install:
           - page.tesk.Refine
           - org.gnome.Loupe
           - org.vinegarhq.Sober
           - org.pulseaudio.pavucontrol
           - org.gnome.Extensions
           - com.mattjakeman.ExtensionManager
           - io.github.pwr_solaar.solaar
           - app.zen_browser.zen
           - io.github.kolunmi.Bazaar
           - app.legcord.Legcord
        remove:
           - org.gnome.eog
   
  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
      - Just Perfection
      - Dash to Dock
      - Control monitor brightness and volume with ddcutil # Note: might not work on gnome 50.
    
  - type: bling
    install:
      - rpmfusion
      
  - type: os-release
    properties:
      ID: kami_os
      NAME: Kami-OS
      PRETTY_NAME: Kami-OS
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
